# Udemy Course: Python A-Z

## Section 3: Fundamentals Of Python

Python Programming A-Z™ © Kirill Eremenko https://www.superdatascience.com 

 This notebook contains exercises from section 3 of the course
 
 A List is a horizontal bookshelf and the elements are books inside the bookshelf
 
 List and array are different.  List are ordered sets of elements 
Note: vectors (in R) are numerated from 1 In python, list numerations starts from 0 Phython can have mix of data type( integers, strings, boolean)

#### Create a List

In [1]:
#My First List
MyFirstList = [3, 45, 56, 732]

In [2]:
MyFirstList

[3, 45, 56, 732]

In [3]:
type(MyFirstList)

list

In [4]:
#List can contain different data types
l2= ["hello", 24, True, 55.3]

In [5]:
print(l2)

['hello', 24, True, 55.3]


In [6]:
#List can contain another List
l3 = ['how are you?', 55, MyFirstList]


In [7]:
print(l3)

['how are you?', 55, [3, 45, 56, 732]]


In [8]:
#Create range with List
range(15) #Python 3 - this is the samw as xrange() in Python 2

range(0, 15)

In [9]:
list(range(15, 20))

[15, 16, 17, 18, 19]

In [36]:
z2 = list(range(100, 121))

In [13]:
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120]

In [14]:
#specify different step
w = list(range(100, 111, 2))

In [15]:
w

[100, 102, 104, 106, 108, 110]

In [16]:
#another example
xy = list(range(50, 400, 50))

In [17]:
xy

[50, 100, 150, 200, 250, 300, 350]

#### Access Elements of a List

In [18]:
w = ['a', 'b', 'c', 'd', 'e']

In [19]:
w

['a', 'b', 'c', 'd', 'e']

In [20]:
#access the first element
w[0]

'a'

In [21]:
#access the second element
w[1]

'b'

In [22]:
#Negative Indexation
#0   1   2   3   4
#-5  -4  -3  -2  -1

In [23]:
#example- different behaviour to R
w[-1]

'e'

In [24]:
#overwrite values

In [25]:
w

['a', 'b', 'c', 'd', 'e']

In [26]:
#overwrite values
w[2] = 63

In [27]:
print(w)

['a', 'b', 63, 'd', 'e']


In [28]:
w[-1] = 55

In [29]:
w

['a', 'b', 63, 'd', 55]

In [30]:
w[4] = xy

In [31]:
print(w)

['a', 'b', 63, 'd', [50, 100, 150, 200, 250, 300, 350]]


#### Slicing

In [32]:
#slicing:taking a subset from a list
#In R programming, slicing is known as subset
#we can use negative index in slicing

#Advance Slicing- uses two colons
#the second colon would return the steps

In [33]:
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [34]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [35]:
#to get all elements
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [36]:
#get all elements after index 2
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [37]:
#get elements less than index 7
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [38]:
#get elements from index 3 to 7
letters[3:8]

['D', 'E', 'F', 'G', 'H']

In [39]:
#Negative Slicing
letters[-7:8]

['D', 'E', 'F', 'G', 'H']

In [40]:
#Negative Slicing too
letters[-7:-2]

['D', 'E', 'F', 'G', 'H']

In [41]:
#Advance slicing

In [42]:
#jumping steps
letters[2:10:3]

['C', 'F', 'I']

In [43]:
letters[::3]

['A', 'D', 'G', 'J']

In [44]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [45]:
letters[::-2]

['J', 'H', 'F', 'D', 'B']

In [46]:
letters[-1:-8:-2]

['J', 'H', 'F', 'D']

In [47]:
letters[6:1:-2]

['G', 'E', 'C']

#### Tuples

In [48]:
#Tuple = immutable list
#uses parenthesis
#you cannot change values in a tuple
#use when you know you won't need to change the values

In [49]:
t1 =(345, 567,987)

In [50]:
t1


(345, 567, 987)

In [51]:
t1[0]

345

In [52]:
t1[2]

987

#### Functions

In [60]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [61]:
mylist_1 = list(range(20,31))

In [62]:
mylist_1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [64]:
len(mylist_1)

11

In [65]:
max(mylist_1)

30

In [66]:
print(mylist_1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


#### Arrays in Python

In [1]:
#Arrarys are a bit similar to list, there take only one datatype
#We have 2 types:
#array arrays-built into Core Python
#numpy arrary-comes with ananconda package(more versatile and flexible)

In [4]:
#Here's a list
l = [23424, 545, 67, 346, -23456]

In [5]:
l

[23424, 545, 67, 346, -23456]

In [2]:
import numpy as np

In [7]:
#here we convert a list to an array
np.array(l)

array([ 23424,    545,     67,    346, -23456])

In [8]:
a = np.array(l)

In [9]:
a

array([ 23424,    545,     67,    346, -23456])

In [13]:
b = [ 5, True, 8.95, 456]

In [14]:
c = np.array(b)

In [15]:
#this converts all datatypes to a float and excludes the Bool
c

array([  5.  ,   1.  ,   8.95, 456.  ])

In [12]:
#arrays have more functions than list
#for example
a.mean()

185.2

In [16]:
a.max()

23424

In [17]:
a.sum()

926

In [19]:
a.min()

-23456

#### Slicing Arrays

In [20]:
#When you slice an array and define it as a new variable
#the values will be replaced in the old arrary, hence you have to create a copy of that array

In [21]:
a

array([-23456,     67,    346,    545,  23424])

In [22]:
a[2:]

array([  346,   545, 23424])

In [23]:
a[2:4]

array([346, 545])

In [24]:
b = a[2:4]

In [25]:
# we are creating a view of array a
b

array([346, 545])

In [26]:
b[0]

346

In [28]:
b[:] = 111

In [29]:
b

array([111, 111])

In [30]:
#two values in array a is replaced with array b
a

array([-23456,     67,    111,    111,  23424])

In [31]:
#instead we can make a copy of (a)
c = a.copy()


In [32]:
c

array([-23456,     67,    111,    111,  23424])

In [33]:
a

array([-23456,     67,    111,    111,  23424])